"""ORM models.

Every model must be imported here so that Alembic autogenerate and
``Base.metadata.create_all`` see the complete schema (C-5).
"""

from netsecops.db.models.audit import (
    GENESIS_HASH,
    AuditAction,
    AuditLog,
    AuditOutcome,
    Setting,
)
from netsecops.db.models.collection import (
    Artifact,
    ArtifactKind,
    Collection,
    Finding,
    FindingKind,
    FindingSeverity,
    FindingStatus,
    Snapshot,
)
from netsecops.db.models.inventory import (
    Credential,
    CredentialAssignment,
    CredentialType,
    Criticality,
    Device,
    DeviceClass,
    DeviceGroup,
    DeviceGroupMember,
    DeviceStatus,
    DeviceTag,
    Site,
    Tag,
    Vendor,
)
from netsecops.db.models.jobs import (
    DeviceJobStatus,
    ErrorClass,
    Job,
    JobDevice,
    JobStatus,
    JobType,
    Schedule,
)
from netsecops.db.models.policy import (
    CheckResult,
    CustomCheck,
    ExceptionScope,
    ExceptionStatus,
    FindingException,
    Policy,
    PolicyAssignment,
    PolicyCheck,
    RiskScore,
)
from netsecops.db.models.user import (
    ApiToken,
    LoginAttempt,
    MFASecret,
    PasswordHistory,
    RefreshToken,
    User,
    UserDeviceGroupScope,
    UserRole,
)
from netsecops.db.models.vulnerability import (
    EolRecordRow,
    FeedSync,
    VulnAdvisory,
    VulnCve,
    VulnMatch,
)

__all__ = [
    "GENESIS_HASH",
    "ApiToken",
    "Artifact",
    "ArtifactKind",
    "AuditAction",
    "AuditLog",
    "AuditOutcome",
    "CheckResult",
    "Collection",
    "Credential",
    "CredentialAssignment",
    "CredentialType",
    "Criticality",
    "CustomCheck",
    "Device",
    "DeviceClass",
    "DeviceGroup",
    "DeviceGroupMember",
    "DeviceJobStatus",
    "DeviceStatus",
    "DeviceTag",
    "EolRecordRow",
    "ErrorClass",
    "ExceptionScope",
    "ExceptionStatus",
    "FeedSync",
    "Finding",
    "FindingException",
    "FindingKind",
    "FindingSeverity",
    "FindingStatus",
    "Job",
    "JobDevice",
    "JobStatus",
    "JobType",
    "LoginAttempt",
    "MFASecret",
    "PasswordHistory",
    "Policy",
    "PolicyAssignment",
    "PolicyCheck",
    "RefreshToken",
    "RiskScore",
    "Schedule",
    "Setting",
    "Site",
    "Snapshot",
    "Tag",
    "User",
    "UserDeviceGroupScope",
    "UserRole",
    "Vendor",
    "VulnAdvisory",
    "VulnCve",
    "VulnMatch",
]
