"""inventory, credential vault, job engine

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-13 09:30:07.932779
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import netsecops.db.types

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # device_groups.path is an ltree materialised path (SRS §5.1), so the extension has
    # to exist before the table that uses it. Creating an extension needs rights the
    # migration role has and the application role does not (SEC-06).
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_groups",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("path", netsecops.db.types.LtreePath(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["device_groups.id"],
            name=op.f("fk_device_groups_parent_id_device_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_groups")),
        sa.UniqueConstraint("org_id", "parent_id", "name", name="uq_device_groups_parent_name"),
    )
    op.create_index(op.f("ix_device_groups_org_id"), "device_groups", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_device_groups_parent_id"), "device_groups", ["parent_id"], unique=False
    )
    op.create_index(
        "ix_device_groups_path", "device_groups", ["path"], unique=False, postgresql_using="gist"
    )
    op.create_table(
        "sites",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
        sa.UniqueConstraint("org_id", "name", name="uq_sites_org_id_name"),
    )
    op.create_index(op.f("ix_sites_org_id"), "sites", ["org_id"], unique=False)
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("colour", sa.String(length=16), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("org_id", "name", name="uq_tags_org_id_name"),
    )
    op.create_index(op.f("ix_tags_org_id"), "tags", ["org_id"], unique=False)
    op.create_table(
        "credentials",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("credential_type", sa.String(length=32), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("encrypted_blob", sa.LargeBinary(), nullable=False),
        sa.Column("key_id", sa.String(length=64), nullable=False),
        sa.Column("external_ref", sa.String(length=512), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_test_succeeded", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_credentials_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credentials")),
        sa.UniqueConstraint("org_id", "name", name="uq_credentials_org_id_name"),
    )
    op.create_index(op.f("ix_credentials_org_id"), "credentials", ["org_id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("mgmt_ip", postgresql.INET(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("fqdn", sa.String(length=255), nullable=True),
        sa.Column("vendor", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=True),
        sa.Column("device_class", sa.String(length=32), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("criticality", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("parent_device_id", sa.UUID(), nullable=True),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("serial_number", sa.String(length=128), nullable=True),
        sa.Column("os_version", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("last_collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("host_key_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("tls_cert_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("ssh_port", sa.Integer(), nullable=False),
        sa.Column("https_port", sa.Integer(), nullable=False),
        sa.Column("connect_timeout", sa.Integer(), nullable=True),
        sa.Column("command_timeout", sa.Integer(), nullable=True),
        sa.Column("jump_host_id", sa.UUID(), nullable=True),
        sa.Column("allow_expert", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("allow_sudo_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["jump_host_id"],
            ["devices.id"],
            name=op.f("fk_devices_jump_host_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_devices_owner_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["parent_device_id"],
            ["devices.id"],
            name=op.f("fk_devices_parent_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_devices_site_id_sites"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("org_id", "mgmt_ip", name="uq_devices_org_id_mgmt_ip"),
    )
    op.create_index(op.f("ix_devices_hostname"), "devices", ["hostname"], unique=False)
    op.create_index(op.f("ix_devices_org_id"), "devices", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_devices_parent_device_id"), "devices", ["parent_device_id"], unique=False
    )
    op.create_index(op.f("ix_devices_serial_number"), "devices", ["serial_number"], unique=False)
    op.create_index(op.f("ix_devices_site_id"), "devices", ["site_id"], unique=False)
    op.create_index("ix_devices_status", "devices", ["status"], unique=False)
    op.create_index("ix_devices_vendor_platform", "devices", ["vendor", "platform"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cron", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("blackout", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_job_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_schedules_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["last_job_id"],
            ["jobs.id"],
            name="fk_schedules_last_job_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
    )
    op.create_index(
        "ix_schedules_enabled_next", "schedules", ["enabled", "next_run_at"], unique=False
    )
    op.create_index(op.f("ix_schedules_org_id"), "schedules", ["org_id"], unique=False)
    op.create_table(
        "credential_assignments",
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credentials.id"],
            name=op.f("fk_credential_assignments_credential_id_credentials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_credential_assignments_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["device_groups.id"],
            name=op.f("fk_credential_assignments_group_id_device_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credential_assignments")),
        sa.UniqueConstraint(
            "credential_id", "device_id", "group_id", name="uq_credential_assignment_target"
        ),
    )
    op.create_index(
        "ix_credential_assignments_device",
        "credential_assignments",
        ["device_id", "priority"],
        unique=False,
    )
    op.create_index(
        "ix_credential_assignments_group",
        "credential_assignments",
        ["group_id", "priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credential_assignments_org_id"), "credential_assignments", ["org_id"], unique=False
    )
    op.create_table(
        "device_group_members",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_group_members_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["device_groups.id"],
            name=op.f("fk_device_group_members_group_id_device_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("device_id", "group_id", name=op.f("pk_device_group_members")),
    )
    op.create_index(
        op.f("ix_device_group_members_org_id"), "device_group_members", ["org_id"], unique=False
    )
    op.create_table(
        "device_tags",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_tags_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_device_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("device_id", "tag_id", name=op.f("pk_device_tags")),
    )
    op.create_index(op.f("ix_device_tags_org_id"), "device_tags", ["org_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column("schedule_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_by_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cancel_requested_by_id"],
            ["users.id"],
            name=op.f("fk_jobs_cancel_requested_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
            name=op.f("fk_jobs_requested_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_jobs_schedule_id_schedules"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    op.create_index(op.f("ix_jobs_correlation_id"), "jobs", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_jobs_org_id"), "jobs", ["org_id"], unique=False)
    op.create_index("ix_jobs_schedule", "jobs", ["schedule_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index("ix_jobs_status_created", "jobs", ["status", "created_at"], unique=False)
    op.create_table(
        "job_devices",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_class", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("retries", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column("command_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credentials.id"],
            name=op.f("fk_job_devices_credential_id_credentials"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_job_devices_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_devices_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_devices")),
    )
    op.create_index(
        "ix_job_devices_device", "job_devices", ["device_id", "created_at"], unique=False
    )
    op.create_index("ix_job_devices_job_status", "job_devices", ["job_id", "status"], unique=False)
    op.create_index(op.f("ix_job_devices_org_id"), "job_devices", ["org_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_user_device_group_scopes_device_group_id_device_groups"),
        "user_device_group_scopes",
        "device_groups",
        ["device_group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    # jobs.schedule_id and schedules.last_job_id reference each other. Autogenerate
    # cannot order a cycle, so the deferred side is added by hand once both tables
    # exist — this is what `use_alter=True` on the model expects.
    op.create_foreign_key(
        "fk_schedules_last_job_id",
        "schedules",
        "jobs",
        ["last_job_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # Drop the deferred constraint first, so the tables can be dropped in any order.
    op.drop_constraint("fk_schedules_last_job_id", "schedules", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_device_group_scopes_device_group_id_device_groups"),
        "user_device_group_scopes",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_job_devices_org_id"), table_name="job_devices")
    op.drop_index("ix_job_devices_job_status", table_name="job_devices")
    op.drop_index("ix_job_devices_device", table_name="job_devices")
    op.drop_table("job_devices")
    op.drop_index("ix_jobs_status_created", table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index("ix_jobs_schedule", table_name="jobs")
    op.drop_index(op.f("ix_jobs_org_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_correlation_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_device_tags_org_id"), table_name="device_tags")
    op.drop_table("device_tags")
    op.drop_index(op.f("ix_device_group_members_org_id"), table_name="device_group_members")
    op.drop_table("device_group_members")
    op.drop_index(op.f("ix_credential_assignments_org_id"), table_name="credential_assignments")
    op.drop_index("ix_credential_assignments_group", table_name="credential_assignments")
    op.drop_index("ix_credential_assignments_device", table_name="credential_assignments")
    op.drop_table("credential_assignments")
    op.drop_index(op.f("ix_schedules_org_id"), table_name="schedules")
    op.drop_index("ix_schedules_enabled_next", table_name="schedules")
    op.drop_table("schedules")
    op.drop_index("ix_devices_vendor_platform", table_name="devices")
    op.drop_index("ix_devices_status", table_name="devices")
    op.drop_index(op.f("ix_devices_site_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_serial_number"), table_name="devices")
    op.drop_index(op.f("ix_devices_parent_device_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_org_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_hostname"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_credentials_org_id"), table_name="credentials")
    op.drop_table("credentials")
    op.drop_index(op.f("ix_tags_org_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_sites_org_id"), table_name="sites")
    op.drop_table("sites")
    op.drop_index("ix_device_groups_path", table_name="device_groups", postgresql_using="gist")
    op.drop_index(op.f("ix_device_groups_parent_id"), table_name="device_groups")
    op.drop_index(op.f("ix_device_groups_org_id"), table_name="device_groups")
    op.drop_table("device_groups")
    # ### end Alembic commands ###
