"""collections, artifacts, snapshots, findings

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-13 11:49:32.622239
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("job_device_id", sa.UUID(), nullable=True),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column("adapter_version", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("partial", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_collections_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_device_id"],
            ["job_devices.id"],
            name=op.f("fk_collections_job_device_id_job_devices"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
    )
    op.create_index(
        "ix_collections_device_created", "collections", ["device_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_collections_org_id"), "collections", ["org_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("request_text", sa.Text(), nullable=False),
        sa.Column("response_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("response_redacted", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_artifacts_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(
        "ix_artifacts_collection_ordinal", "artifacts", ["collection_id", "ordinal"], unique=False
    )
    op.create_index(op.f("ix_artifacts_org_id"), "artifacts", ["org_id"], unique=False)
    op.create_index("ix_artifacts_sha256", "artifacts", ["sha256"], unique=False)
    op.create_table(
        "snapshots",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("normalized_hash", sa.String(length=64), nullable=False),
        sa.Column("config_redacted", sa.Text(), nullable=False),
        sa.Column("ncm", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ncm_version", sa.String(length=16), nullable=False),
        sa.Column("parser_platform", sa.String(length=64), nullable=True),
        sa.Column("parse_coverage", sa.Integer(), nullable=True),
        sa.Column("unparsed_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_baseline", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("baseline_pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("baseline_pinned_by_id", sa.UUID(), nullable=True),
        sa.Column("duplicate_of_id", sa.UUID(), nullable=True),
        sa.Column("seen_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["baseline_pinned_by_id"],
            ["users.id"],
            name=op.f("fk_snapshots_baseline_pinned_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_snapshots_collection_id_collections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_snapshots_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"],
            ["snapshots.id"],
            name=op.f("fk_snapshots_duplicate_of_id_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_snapshots")),
    )
    op.create_index(
        "ix_snapshots_config_hash", "snapshots", ["device_id", "config_hash"], unique=False
    )
    op.create_index(
        "ix_snapshots_device_created", "snapshots", ["device_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_snapshots_org_id"), "snapshots", ["org_id"], unique=False)
    op.create_index(
        "uq_snapshots_one_baseline_per_device",
        "snapshots",
        ["device_id"],
        unique=True,
        postgresql_where=sa.text("is_baseline"),
    )
    op.create_table(
        "findings",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("check_id", sa.String(length=100), nullable=True),
        sa.Column("cve_id", sa.String(length=32), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("snapshot_id", sa.UUID(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurrences", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_findings_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_findings_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.id"],
            name=op.f("fk_findings_snapshot_id_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint("device_id", "fingerprint", name="uq_findings_device_fingerprint"),
    )
    op.create_index("ix_findings_device_kind", "findings", ["device_id", "kind"], unique=False)
    op.create_index(op.f("ix_findings_org_id"), "findings", ["org_id"], unique=False)
    op.create_index("ix_findings_status_severity", "findings", ["status", "severity"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_findings_status_severity", table_name="findings")
    op.drop_index(op.f("ix_findings_org_id"), table_name="findings")
    op.drop_index("ix_findings_device_kind", table_name="findings")
    op.drop_table("findings")
    op.drop_index(
        "uq_snapshots_one_baseline_per_device",
        table_name="snapshots",
        postgresql_where=sa.text("is_baseline"),
    )
    op.drop_index(op.f("ix_snapshots_org_id"), table_name="snapshots")
    op.drop_index("ix_snapshots_device_created", table_name="snapshots")
    op.drop_index("ix_snapshots_config_hash", table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_index("ix_artifacts_sha256", table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_org_id"), table_name="artifacts")
    op.drop_index("ix_artifacts_collection_ordinal", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_collections_org_id"), table_name="collections")
    op.drop_index("ix_collections_device_created", table_name="collections")
    op.drop_table("collections")
    # ### end Alembic commands ###
